/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AdaptiveRouteImport } from './routes/adaptive'
import { Route as AiAnalysisRouteImport } from './routes/ai-analysis'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as EcgRouteImport } from './routes/ecg'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as LiveRouteImport } from './routes/live'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SleepRouteImport } from './routes/sleep'
import { Route as TelemetryRouteImport } from './routes/telemetry'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as AlertsIndexRouteImport } from './routes/alerts/index'
import { Route as AlertsIdRouteImport } from './routes/alerts/$id'
import { Route as PatientsIndexRouteImport } from './routes/patients/index'
import { Route as PatientsIdRouteImport } from './routes/patients/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaptiveRoute = AdaptiveRouteImport.update({
  id: '/adaptive',
  path: '/adaptive',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAnalysisRoute = AiAnalysisRouteImport.update({
  id: '/ai-analysis',
  path: '/ai-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const EcgRoute = EcgRouteImport.update({
  id: '/ecg',
  path: '/ecg',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SleepRoute = SleepRouteImport.update({
  id: '/sleep',
  path: '/sleep',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemetryRoute = TelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsIndexRoute = AlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsIdRoute = AlertsIdRouteImport.update({
  id: '/alerts/$id',
  path: '/alerts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIdRoute = PatientsIdRouteImport.update({
  id: '/patients/$id',
  path: '/patients/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/adaptive': typeof AdaptiveRoute
  '/ai-analysis': typeof AiAnalysisRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/dashboard': typeof DashboardRoute
  '/devices': typeof DevicesRoute
  '/ecg': typeof EcgRoute
  '/emergency': typeof EmergencyRoute
  '/live': typeof LiveRoute
  '/models': typeof ModelsRoute
  '/performance': typeof PerformanceRoute
  '/reports': typeof ReportsRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/sleep': typeof SleepRoute
  '/telemetry': typeof TelemetryRoute
  '/trends': typeof TrendsRoute
  '/alerts/$id': typeof AlertsIdRoute
  '/patients/$id': typeof PatientsIdRoute
  '/alerts/': typeof AlertsIndexRoute
  '/patients/': typeof PatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/adaptive': typeof AdaptiveRoute
  '/ai-analysis': typeof AiAnalysisRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/dashboard': typeof DashboardRoute
  '/devices': typeof DevicesRoute
  '/ecg': typeof EcgRoute
  '/emergency': typeof EmergencyRoute
  '/live': typeof LiveRoute
  '/models': typeof ModelsRoute
  '/performance': typeof PerformanceRoute
  '/reports': typeof ReportsRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/sleep': typeof SleepRoute
  '/telemetry': typeof TelemetryRoute
  '/trends': typeof TrendsRoute
  '/alerts/$id': typeof AlertsIdRoute
  '/patients/$id': typeof PatientsIdRoute
  '/alerts': typeof AlertsIndexRoute
  '/patients': typeof PatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/adaptive': typeof AdaptiveRoute
  '/ai-analysis': typeof AiAnalysisRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/dashboard': typeof DashboardRoute
  '/devices': typeof DevicesRoute
  '/ecg': typeof EcgRoute
  '/emergency': typeof EmergencyRoute
  '/live': typeof LiveRoute
  '/models': typeof ModelsRoute
  '/performance': typeof PerformanceRoute
  '/reports': typeof ReportsRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/sleep': typeof SleepRoute
  '/telemetry': typeof TelemetryRoute
  '/trends': typeof TrendsRoute
  '/alerts/$id': typeof AlertsIdRoute
  '/patients/$id': typeof PatientsIdRoute
  '/alerts/': typeof AlertsIndexRoute
  '/patients/': typeof PatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/adaptive'
    | '/ai-analysis'
    | '/ai-assistant'
    | '/dashboard'
    | '/devices'
    | '/ecg'
    | '/emergency'
    | '/live'
    | '/models'
    | '/performance'
    | '/reports'
    | '/research'
    | '/settings'
    | '/sleep'
    | '/telemetry'
    | '/trends'
    | '/alerts/$id'
    | '/patients/$id'
    | '/alerts/'
    | '/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/adaptive'
    | '/ai-analysis'
    | '/ai-assistant'
    | '/dashboard'
    | '/devices'
    | '/ecg'
    | '/emergency'
    | '/live'
    | '/models'
    | '/performance'
    | '/reports'
    | '/research'
    | '/settings'
    | '/sleep'
    | '/telemetry'
    | '/trends'
    | '/alerts/$id'
    | '/patients/$id'
    | '/alerts'
    | '/patients'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/adaptive'
    | '/ai-analysis'
    | '/ai-assistant'
    | '/dashboard'
    | '/devices'
    | '/ecg'
    | '/emergency'
    | '/live'
    | '/models'
    | '/performance'
    | '/reports'
    | '/research'
    | '/settings'
    | '/sleep'
    | '/telemetry'
    | '/trends'
    | '/alerts/$id'
    | '/patients/$id'
    | '/alerts/'
    | '/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AdaptiveRoute: typeof AdaptiveRoute
  AiAnalysisRoute: typeof AiAnalysisRoute
  AiAssistantRoute: typeof AiAssistantRoute
  DashboardRoute: typeof DashboardRoute
  DevicesRoute: typeof DevicesRoute
  EcgRoute: typeof EcgRoute
  EmergencyRoute: typeof EmergencyRoute
  LiveRoute: typeof LiveRoute
  ModelsRoute: typeof ModelsRoute
  PerformanceRoute: typeof PerformanceRoute
  ReportsRoute: typeof ReportsRoute
  ResearchRoute: typeof ResearchRoute
  SettingsRoute: typeof SettingsRoute
  SleepRoute: typeof SleepRoute
  TelemetryRoute: typeof TelemetryRoute
  TrendsRoute: typeof TrendsRoute
  AlertsIdRoute: typeof AlertsIdRoute
  PatientsIdRoute: typeof PatientsIdRoute
  AlertsIndexRoute: typeof AlertsIndexRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adaptive': {
      id: '/adaptive'
      path: '/adaptive'
      fullPath: '/adaptive'
      preLoaderRoute: typeof AdaptiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-analysis': {
      id: '/ai-analysis'
      path: '/ai-analysis'
      fullPath: '/ai-analysis'
      preLoaderRoute: typeof AiAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecg': {
      id: '/ecg'
      path: '/ecg'
      fullPath: '/ecg'
      preLoaderRoute: typeof EcgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sleep': {
      id: '/sleep'
      path: '/sleep'
      fullPath: '/sleep'
      preLoaderRoute: typeof SleepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemetry': {
      id: '/telemetry'
      path: '/telemetry'
      fullPath: '/telemetry'
      preLoaderRoute: typeof TelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/': {
      id: '/alerts/'
      path: '/alerts'
      fullPath: '/alerts/'
      preLoaderRoute: typeof AlertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/$id': {
      id: '/alerts/$id'
      path: '/alerts/$id'
      fullPath: '/alerts/$id'
      preLoaderRoute: typeof AlertsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$id': {
      id: '/patients/$id'
      path: '/patients/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof PatientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AdaptiveRoute: AdaptiveRoute,
  AiAnalysisRoute: AiAnalysisRoute,
  AiAssistantRoute: AiAssistantRoute,
  DashboardRoute: DashboardRoute,
  DevicesRoute: DevicesRoute,
  EcgRoute: EcgRoute,
  EmergencyRoute: EmergencyRoute,
  LiveRoute: LiveRoute,
  ModelsRoute: ModelsRoute,
  PerformanceRoute: PerformanceRoute,
  ReportsRoute: ReportsRoute,
  ResearchRoute: ResearchRoute,
  SettingsRoute: SettingsRoute,
  SleepRoute: SleepRoute,
  TelemetryRoute: TelemetryRoute,
  TrendsRoute: TrendsRoute,
  AlertsIdRoute: AlertsIdRoute,
  PatientsIdRoute: PatientsIdRoute,
  AlertsIndexRoute: AlertsIndexRoute,
  PatientsIndexRoute: PatientsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
